#    -*- mode: org -*-

Archived entries from file /home/alper/ebloc-broker/broker/todo.org


* DONE Fix updateProviderPrices
CLOSED: [2023-03-13 Mon 01:20]
:PROPERTIES:
:ARCHIVE_TIME: 2023-03-13 Mon 01:20
:ARCHIVE_FILE: ~/ebloc-broker/broker/todo.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: todo
:ARCHIVE_TODO: DONE
:END:
#+begin_src python
TypeError: updateProviderPrices '['0.001 usd', '0.0001 cent', '0.0001 cent', '0.0001 cent']' - Cannot convert str '0.001 usd' to wei.
An exception of type TypeError occurred. Arguments:
#+end_src
* DONE
CLOSED: [2022-04-04 Mon 10:34]
:PROPERTIES:
:ARCHIVE_TIME: 2022-04-04 Mon 10:34
:ARCHIVE_FILE: ~/ebloc-broker/broker/TODO.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: TODO
:ARCHIVE_TODO: DONE
:END:

__ https://stackoverflow.com/a/29243206/2402577

#+begin_src python
import zlib

a = "this string needs compressing"
a = zlib.compress(a.encode())
print(zlib.decompress(a).decode())
#+end_src
* DONE
CLOSED: [2022-05-26 Thu 09:56]
:PROPERTIES:
:ARCHIVE_TIME: 2022-05-26 Thu 09:56
:ARCHIVE_FILE: ~/ebloc-broker/broker/TODO.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: TODO
:ARCHIVE_TODO: DONE
:END:
carry `run_with_output` into tools

convert all ~run(~ into ~run_with_output(~
* DONE remove all /home/username
CLOSED: [2022-06-20 Mon 20:01]
:PROPERTIES:
:ARCHIVE_TIME: 2022-06-20 Mon 20:01
:ARCHIVE_FILE: ~/ebloc-broker/broker/TODO.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: TODO
:ARCHIVE_TODO: DONE
:END:
* DONE re-run the tests
CLOSED: [2022-07-02 Sat 11:55]
:PROPERTIES:
:ARCHIVE_TIME: 2022-07-02 Sat 11:55
:ARCHIVE_FILE: ~/ebloc-broker/broker/TODO.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: TODO
:ARCHIVE_TODO: DONE
:END:
* DONE check before submitting job from the requester
CLOSED: [2022-07-14 Thu 12:46]
:PROPERTIES:
:ARCHIVE_TIME: 2022-07-14 Thu 12:46
:ARCHIVE_FILE: ~/ebloc-broker/broker/gpg/README.org
:ARCHIVE_OLPATH: GNU Privacy
:ARCHIVE_CATEGORY: README
:ARCHIVE_TODO: DONE
:END:
#+begin_src bash
# key=$(~/ebloc-broker/broker/bash_scripts/get_gpg_fingerprint.sh)
key=$(gpg --list-secret-keys --keyid-format LONG <email>)
echo $key && gpg --list-keys $key
gpg --verbose --keyserver hkps://keyserver.ubuntu.com --send-keys $key
#+end_src
* DONE if registered data requested data_in for that has should be 0
CLOSED: [2022-11-13 Sun 11:28]
:PROPERTIES:
:ARCHIVE_TIME: 2022-11-13 Sun 11:28
:ARCHIVE_FILE: ~/ebloc-broker/broker/TODO.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: TODO
:ARCHIVE_TODO: DONE
:END:

* DONE replace ~eudat~ with ~b2drop~
CLOSED: [2023-01-01 Sun 20:26]
:PROPERTIES:
:ARCHIVE_TIME: 2023-01-01 Sun 20:26
:ARCHIVE_FILE: ~/ebloc-broker/broker/TODO.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: TODO
:ARCHIVE_TODO: DONE
:END:

* DONE
CLOSED: [2023-03-15 Wed 02:16]
:PROPERTIES:
:ARCHIVE_TIME: 2023-03-15 Wed 02:16
:ARCHIVE_FILE: ~/ebloc-broker/broker/todo.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: todo
:ARCHIVE_TODO: DONE
:END:
#+begin_src bash
provider's available_core_num=4
provider's price_core_min=1.0E-7 usd
 * trying to connect into /ip4/68.183.79.44/tcp/4001/p2p/12D3KooWQ9eXnXRs5MeCP11tgvcWENsUs4JUMBBESfDX3QDGf548

E: connection into provider's IPFS node via swarm is not accomplished.
Try: nc <ip> 4001
Traceback (most recent call last):
  File "/home/alper/ebloc-broker/broker/libs/ipfs.py", line 234, in swarm_connect
    raise Exception(e)
Exception: Error: connect 12D3KooWQ9eXnXRs5MeCP11tgvcWENsUs4JUMBBESfDX3QDGf548 failurfailed to dial 12D3KooWQ9eXnXRs5MeCP11tgvcWENsUs4JUMBBESfDX3QDGf548:
  * /ip4/68.183.79.44/tcp/4001 failed to negotiate security protocol: peer id mismatch: expected 12D3KooWQ9eXnXRs5MeCP11tgvcWENsUs4JUMBBESfDX3QDGf548, but remote key matches
12D3KooWP77QwRFYkEeat23hGNdDQ36VyCiEP56RaRf585QzauTD
E: Error: connect 12D3KooWQ9eXnXRs5MeCP11tgvcWENsUs4JUMBBESfDX3QDGf548 failurfailed to dial 12D3KooWQ9eXnXRs5MeCP11tgvcWENsUs4JUMBBESfDX3QDGf548:
  * /ip4/68.183.79.44/tcp/4001 failed to negotiate security protocol: peer id mismatch: expected 12D3KooWQ9eXnXRs5MeCP11tgvcWENsUs4JUMBBESfDX3QDGf548, but remote key matches
12D3KooWP77QwRFYkEeat23hGNdDQ36VyCiEP56RaRf585QzauTD
#+end_src

* DONE during job submittion check web3 connection
CLOSED: [2023-04-05 Wed 15:45]
:PROPERTIES:
:ARCHIVE_TIME: 2023-04-05 Wed 15:45
:ARCHIVE_FILE: ~/ebloc-broker/broker/todo.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: todo
:ARCHIVE_TODO: DONE
:END:

* DONE verify_data_list= returns empty
CLOSED: [2023-05-09 Tue 22:09]
:PROPERTIES:
:ARCHIVE_TIME: 2023-05-09 Tue 22:09
:ARCHIVE_FILE: ~/ebloc-broker/broker/todo.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: todo
:ARCHIVE_TODO: DONE
:END:

* DONE ipfs lock
CLOSED: [2023-05-10 Wed 22:01]
:PROPERTIES:
:ARCHIVE_TIME: 2023-05-10 Wed 22:01
:ARCHIVE_FILE: ~/ebloc-broker/broker/todo.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: todo
:ARCHIVE_TODO: DONE
:END:
#+begin_src bash
Exception in thread 44d29fef9df148628e2b6ee50b695866:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alper/ebloc-broker/broker/drivers/ipfs.py", line 70, in run
    log(f"==> is_ipfs_hash_locally_cached={cfg.ipfs.is_hash_locally_cached(self.job_key)}")
  File "/home/alper/ebloc-broker/broker/libs/ipfs.py", line 72, in is_hash_locally_cached
    ipfs_refs_local = run(["ipfs", "refs", "local"]).split("\n")
  File "/home/alper/ebloc-broker/broker/_utils/tools.py", line 364, in run
    raise Exception from None  # prevents tree of trace
Exception
#+end_src

* DONE Traceback (most recent call last):
CLOSED: [2023-05-11 Thu 19:23]
:PROPERTIES:
:ARCHIVE_TIME: 2023-05-11 Thu 19:23
:ARCHIVE_FILE: ~/ebloc-broker/broker/todo.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: todo
:ARCHIVE_TODO: DONE
:END:
#+begin_src
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alper/ebloc-broker/broker/drivers/ipfs.py", line 134, in run
    raise e
  File "/home/alper/ebloc-broker/broker/drivers/ipfs.py", line 132, in run
    _git.initialize_check(target)
  File "/home/alper/ebloc-broker/broker/libs/_git.py", line 35, in initialize_check
    raise e
  File "/home/alper/ebloc-broker/broker/libs/_git.py", line 32, in initialize_check
    add_all()
  File "/home/alper/ebloc-broker/broker/libs/_git.py", line 208, in add_all
    raise e
  File "/home/alper/ebloc-broker/broker/libs/_git.py", line 205, in add_all
    raise e
  File "/home/alper/ebloc-broker/broker/libs/_git.py", line 201, in add_all
    repo.git.commit("-m", "update")
  File "/home/alper/venv/lib/python3.8/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(-9)
  cmdline: git commit -m update
#+end_src

* DONE Kayitli olsan gdrive ile == "gdrive about' is match? check
CLOSED: [2023-06-26 Mon 13:43]
:PROPERTIES:
:ARCHIVE_TIME: 2023-06-26 Mon 13:43
:ARCHIVE_FILE: ~/ebloc-broker/broker/TODO.org
:ARCHIVE_OLPATH: TASKS
:ARCHIVE_CATEGORY: TODO
:ARCHIVE_TODO: DONE
:END:
