                            *outline*
* TASKS
** TODO log ~dataTransferIn~ in the contract
- self.eBlocBroker.decode_input(input)
- testte dataTransferIn hep [0, 0, 0, 0] olarak hesaplanmis?
** TODO patch bdrop and google-drive
** TODO verify downloaded data
** TODO convert ~ipfsID~ into ~ipfsAddress~ in the ~eBlocBrokerInterface.sol~
** TODO Test updated code in 2 machines with your test cast submitting job.
** TODO IPFS inside docker should be swarm connect from outside
** TODO Do demo video do from https://asciinema.org/a/480875 , you can copy string from the video
** TODO check ? dataPricesSetBlockNum > 0 is true at checkRegisteredData() for registered data usage
** TODO check ? in smart-contract in ~internal~ calls is if memory variable updated does it updated as well on where it called from
** TODO token
– https://docs.openzeppelin.com/contracts/2.x/erc20
– https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC20
** TODO get_transaction_receipt console'a ekle
** TODO rootless docker in the compute nodes
https://serverfault.com/a/1078434/395276
** TODO https://www.mturk.com
** TODO apply patched for all the folders
** TODO Later do, when cache time is completed:
   oc.decline_remote_share(int(<share_id>)) to cancel shared folder at
   end_code or after some time later
** TODO /* Sets the job's state (stateCode) which is obtained from Slurm */
Slurm status should be set on the receiveDeposit call not setJobStatus
** TODO DAS2-fs1-2003-1.swf
   Starting from // 5955  9447070
   __ https://www.cse.huji.ac.il/labs/parallel/workload/l_das2/index.html
** TODO oc may have "owncloud.owncloud.HTTPResponseError: HTTP error: 401" error
** TODO Some code should go into utils.py
   Some functıons are public that should carried into ~utils.py~
** TODO for workflow visualization: https://github.com/mermaid-js/mermaid
** TODO remove _balance? could be not needed.
** TODO BUGS
#+begin_src python
Failed to share file: googleapi: Error 403: Rate limit exceeded. User message: "Sorry, you have exceeded your sharing quota.", sharingRateLimitExceeded
#+end_src
** TODO fetch b2drop empty size
** TODO investigate store web3 ebb object and read reread from it using picle
** TODO timeout bloxberg
+ maybe apply timeout wrapper for the getter functions
#+begin_src python
  File "/home/alper/venv/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='core.bloxberg.org', port=443): Read timed out. (read timeout=30)
An exception of type ReadTimeout occurred. Arguments:
(ReadTimeoutError("HTTPSConnectionPool(host='core.bloxberg.org', port=443): Read timed out. (read timeout=30)"),)

Traceback (most recent call last):
  File "/home/alper/ebloc-broker/broker/imports.py", line 155, in connect_to_eblocbroker
    project = project.load(env.CONTRACT_PROJECT_PATH)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 780, in load
    return Project(name, project_path)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 188, in __init__
    self.load()
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 262, in load
    self._load_deployments()
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 382, in
_load_deployments
    contract = ProjectContract(self, build, build_json.stem)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 1308, in
__init__
    _DeployedContractBase.__init__(self, address, owner, tx)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 706, in
__init__
    self.bytecode = web3.eth.get_code(address).hex()[2:]
  File "/home/alper/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/alper/venv/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line
90, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line
40, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py",
line 105, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in
make_request
    raw_response = make_post_request(
  File "/home/alper/venv/lib/python3.8/site-packages/web3/_utils/request.py", line 113, in
make_post_request
    response.raise_for_status()
  File "/home/alper/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in
raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://core.bloxberg.org/
An exception of type HTTPError occurred. Arguments:
('502 Server Error: Bad Gateway for url: https://core.bloxberg.org/',)
Traceback (most recent call last):
  File "/home/alper/ebloc-broker/broker/imports.py", line 47, in connect
    connect_to_eblocbroker()
  File "/home/alper/ebloc-broker/broker/imports.py", line 162, in connect_to_eblocbroker
    raise e
  File "/home/alper/ebloc-broker/broker/imports.py", line 155, in connect_to_eblocbroker
    project = project.load(env.CONTRACT_PROJECT_PATH)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 780, in load
    return Project(name, project_path)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 188, in __init__
    self.load()
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 262, in load
    self._load_deployments()
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/project/main.py", line 382, in
_load_deployments
    contract = ProjectContract(self, build, build_json.stem)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 1308, in
__init__
    _DeployedContractBase.__init__(self, address, owner, tx)
  File "/home/alper/venv/lib/python3.8/site-packages/brownie/network/contract.py", line 706, in
__init__
    self.bytecode = web3.eth.get_code(address).hex()[2:]
  File "/home/alper/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/alper/venv/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line
90, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in
middleware
    response = make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line
40, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py",
line 105, in middleware
    return make_request(method, params)
  File "/home/alper/venv/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in
make_request
    raw_response = make_post_request(
  File "/home/alper/venv/lib/python3.8/site-packages/web3/_utils/request.py", line 113, in
make_post_request
    response.raise_for_status()
  File "/home/alper/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in
raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://core.bloxberg.org/
An exception of type HTTPError occurred. Arguments:
('502 Server Error: Bad Gateway for url: https://core.bloxberg.org/',)
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
warning: web3 is not connected into BLOXBERG
Trying again...
Traceback (most recent call last):
  File "/home/alper/ebloc-broker/broker/imports.py", line 96, in connect_to_web3
    connect_to_web3()  #: trying again
  File "/home/alper/ebloc-broker/broker/imports.py", line 87, in connect_to_web3
    _connect_to_web3()
  File "/home/alper/ebloc-broker/broker/imports.py", line 64, in _connect_to_web3
    raise Exception(f"ping to {host} failed")
Exception: ping to https://core.bloxberg.org failed

#+end_src
** TODO

- name: bloxberg_host (Bloxberg)
        id: bloxberg_host
        chainid: 8995
        host: http://127.0.0.1:8545/
